apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: frontend-udagram
  labels: 
    app: frontend-udagram 
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: frontend-udagram 
  template: 
    metadata: 
      labels: 
        app: frontend-udagram 
    spec: 
      containers: 
      - name: frontend-udagram
        image: phoint/udagram-frontend:v0.1.8
        ports: 
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m" 