apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-udagram
  name: frontend-udagram
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
    protocol: TCP
  selector:
    app: frontend-udagram