apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: reverse-proxy
  labels: 
    app: reverse-proxy
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: reverse-proxy
  template: 
    metadata: 
      labels: 
        app: reverse-proxy 
    spec: 
      containers: 
      - name: reverse-proxy
        image: phoint/udagram-reverseproxy:v0.1.8
        ports: 
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      restartPolicy: Always