# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      # build and push Docker image
      - run:
	        name: build feed api
	        command: |       		
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed phoint/udagram-api-feed:v$TAG
      - run:
          name: build user api
          command: |
      	    docker build -t udagram-api-user ./udagram-api-user
      	    docker tag udagram-api-user phoint/udagram-api-user:v$TAG
      - run:
      	  name: build frontend
      	  command: |
      	    docker build -t udagram-frontend ./udagram-frontend
      	    docker tag udagram-frontend phoint/udagram-frontend:v$TAG
      - run:
      	  name: build reverse proxy
      	  command: |
      	    docker build -t udagram-reverseproxy ./udagram-reverseproxy
      	    docker tag udagram-reverseproxy phoint/udagram-reverseproxy:v$TAG
      - run:
          name: push images
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push phoint/udagram-api-feed:v$TAG
            docker push phoint/udagram-api-user:v$TAG
            docker push phoint/udagram-frontend:v$TAG
            docker push phoint/udagram-reverseproxy:v$TAG
